### ISSUE TITLE
Navbar not appearing on mobile view

### ISSUE THREAD

**Issue by alifmahardhika** [app-generator/django-datta-able#1]
First of all, I have to say that this app is wonderful, and the designs are just beautiful. However, I can't seem to display the navbar properly in mobile views. Any help would be very much appreciated. Thank you and keep up the good work!

**Comment by app-generator** [comment]
Hello @alifmahardhika, 

Thank you for using our products. 
Please provide a screenshot and more information regarding the screen resolution. 

If is something that we can fix, we will provide a patch soon. 
2nd option is to forward the issue to the UI Kit provider, .. this might take a while, being a free kit. 

- AppSeed Support

**Comment by alifmahardhika** [comment]
Hi! Thank you for the fast response. I'm using the demo web app [()](https://django-dashboard-dattaable.appseed.us/) for example, but the navbar display bug can be reproduced on local development app run on my localhost. Below is some information I think might be useful:

1.  With1048x445 (responsive) or bigger ratio, the navbar is displayed correctly as follows:
![image](https://user-images.githubusercontent.com/54898652/88026858-a98b5080-cb60-11ea-8f53-17529bb91a0d.png)

2. With a lower screen ratio, the navbar seems to disappear and it seems there is no way to make it appear. 
On Iphone X screen ratio:
![image](https://user-images.githubusercontent.com/54898652/88027339-4d74fc00-cb61-11ea-9e53-1f9e5b95c56e.png)
Using responsive 972 x 1156 ratio:
![image](https://user-images.githubusercontent.com/54898652/88027435-709fab80-cb61-11ea-8432-54e57f3e80c1.png)


I'll try forwarding the issue to UI Kit provider too. Thank you again for your help!

**Comment by jossgillet** [comment]
Hi @alifmahardhika - I'm facing the same issue. Did you manage to resolve it ? Thanks

**Comment by app-generator** [comment]
CodedThemes will provide a fix. 
Once we have the patch, the codebase gets an update asap.

Thank you!

**Comment by SFARPak** [comment]
Did someone find work around?

Thanks in advance.

**Comment by app-generator** [comment]
The product is scheduled for Bootstrap 5 update.

**Comment by app-generator** [comment]
Hello guys! 

The product is scheduled for BS5 migration. 

For help & LIVE assistance, please access: 

https://appseed.us/support/

Ty!
