### ISSUE TITLE
How to open the sidebar with a button

### ISSUE THREAD

**Issue by EdaDeniz** [app-generator/django-datta-able#12]
In this theme, we need to move the mouse aside to open the sidebar but I want to use a button instead of that. How can I do?

**Comment by TheSnowGuru** [comment]
yeah need to fix it....

**Comment by app-generator** [comment]
Hello guys! 

This behavior is the default one used in all kits crafted by [CodedThemes](https://bit.ly/37fF9RT)

For further assistance, please access: 

https://appseed.us/support/

Ty!
