### ISSUE TITLE
Installation as admin theme

### ISSUE THREAD

**Issue by sridhar562345** [app-generator/django-datta-able#13]
Can we install this as a custom admin theme?

**Comment by app-generator** [comment]
Hello @sridhar562345, 

The project is not built for the `admin` section. The [premium version](https://appseed.us/admin-dashboards/django-dashboard-dattaable-pro) (startup license) comes with `admin theme`. 

We provide OSS versions for the `admin` section, but for other products:
- https://github.com/app-generator/django-admin-volt
- https://github.com/app-generator/django-admin-black

Both are usable via PyPi.

**Comment by sridhar562345** [comment]
Thanks for the quick response.
