### ISSUE TITLE
disabling the forced login / redirect

### ISSUE THREAD

**Issue by nubonics** [app-generator/django-datta-able#16]
how to remove the redirect to the login page so i can create a normal webpage with an option for the user to create an account to access the dashboard?

**Comment by app-generator** [comment]
Hello @nubonics, 

A quick fix is to remove the `@login_required(login_url="/login/")` decorator from `apps/home/views.py`

https://github.com/app-generator/django-datta-able/blob/master/apps/home/views.py

Let us know your progresss

**Comment by nubonics** [comment]
I think i worded that poorly.

What I am looking to do is use dattable as a template for the dashboard, while creating my own product page [ dont think dattable has one ].

So I am creating a SaaS application, creating a home / features / pricing page and a call to action, and from there, the user/client can pay a subscription fee to access the dashboard. Hopefully that makes more sense on what i mean by disabling the forced login. I want to keep the forced login to access the dashboard, but I dont want anyone to be forced to visit the login page without having access to the product pages.

**Comment by nubonics** [comment]
seems i have solved the issue by learning django basics and clearing unused docker containers.

**Comment by app-generator** [comment]
Hello @nubonics 

Let us know if you need further assistance.
