### ISSUE TITLE
Form field not displaying in Page

### ISSUE THREAD

**Issue by mapajama** [app-generator/django-datta-able#27]
Good day,
I have been having a challenge in displaying form fields in a template/home/page-blank.html page
Here are the steps I took:
1. Used requirement.txt to setup Django-datta-able in a folder after venv env
2. My view is set as: 
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render
from .forms import ClientForm
def blank_page(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ClientForm()
    print(form.errors)
    return render(request, 'page-blank.html', {'form': form})

4. forms.py : from django import forms
from .models import Client

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email', 'phone']

5. Template in templates/home/page-blank.html :                                                 
6.                                            <p><h2>Add a New Client</h2>
                                                    <form method="post">
                                                        {% csrf_token %}
                                                        {{ form.as_p }}
                                                        <input type="submit" value="Submit">
                                                    </form>
                                                </p>
7. Model:
from django.db import models
from django.contrib.auth.models import User
# models.py

class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

8. The URL was not tampered with:
from django.urls import path, re_path
from apps.home import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

http://127.0.0.1:8000/page-blank.html
![image](https://user-images.githubusercontent.com/53023193/219688394-d3df8ce9-7d3b-41aa-a0cb-5925f3fe2305.png)

**Comment by snow-bean** [comment]
var not displaying in index.html:  
---------------------------------
def index(request):
  context = {
    'segment': 'index',
   'a1'='yyy'
  }
  return render(request, "pages/index.html", context)

index.html  >{{ a1 }}
---------------------------------------
i want to display 'yyy' in the index.html.but when i run the server  ,the page displayed normally but 'yyy' was not display .  may i know why ?thanks!

**Comment by snow-bean** [comment]
i also meet the similay question, have you handle that ?

**Comment by app-generator** [comment]
Fixed in version `v1.0.23`.
Please check.
