### ISSUE TITLE
var not displaying in index.html:

### ISSUE THREAD

**Issue by snow-bean** [app-generator/django-datta-able#28]
def index(request):
context = {
'segment': 'index',
'a1'='yyy'
}
return render(request, "pages/index.html", context)

index.html >{{ a1 }}
i want to display 'yyy' in the index.html.but when i run the server ,the page displayed normally but 'yyy' was not display . may i know why ?thanks!

**Comment by HyoungSooo** [comment]
in home/urls.py

remove from admin_datta import views
and then add from . import views
it works for me
