### ISSUE TITLE
Auth URLs

### ISSUE THREAD

**Issue by AInME93** [app-generator/django-datta-able#3]
Hi y'all

Just started learning Django, decided to start play around with this template. Just stuck with one thing: the tuts show that with the default django admin I can access Models with a general view like: .../admin/auth/users or .../admin/auth/groups. For some reason I can't do that with this template, I get a 404. When I flat out type .../admin, i get a 500.

Were the default urls changed somehow?

**Comment by app-generator** [comment]
Hello,

Thank you for using this product. To get rid of that 500, please access the
admin section using "admin/" path (with a slash at the end).
If you are using new models, follow this set up to make them visible in the
admin section:

http://www.john-player.com/django/how-to-register-a-model-with-django-admin/

Let us know if you need further assistance.

**Comment by AInME93** [comment]
Yeah the trailing forward slash was the issue.

Sorry I didnt close the issue earlier, I had switched to a different project for a while and forgotten about the one which made me raise this issue.

Thanks and have a nice day!
