### ISSUE TITLE
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully

### ISSUE THREAD

**Issue by chinnu0505** [app-generator/django-datta-able#30]
I keep getting this error when trying to create a new project. I've installed all the requirements and properly configured my PostgreSQL database too

Full Traceback:

`Traceback (most recent call last):
  File "C:\Users\Praneeth\AppData\Local\Temp\tmpouuf66dn.py", line 48, in <module>
    post_hook()
  File "C:\Users\Praneeth\AppData\Local\Temp\tmpouuf66dn.py", line 22, in post_hook
    copy_tree(fromDirectory, toDirectory)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\dir_util.py", line 123, in copy_tree
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: cannot copy tree './tmp/apps/static': not a directory
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)`

Here's the full configuration/command prompt log:
![Inkedcmd_4MdGN6Bmk4](https://github.com/app-generator/django-datta-able/assets/122245112/05dcb9bb-dcfd-4e00-a9f0-38b37adcba81)

Any idea what's going on? I got the original cookiecutter working just fine.

**Comment by app-generator** [comment]
Hello @chinnu0505 

The [Django Cookie-Cutter](https://github.com/app-generator/cookiecutter-django) is deprecated by the [Rocket Generator](https://app-generator.dev/) service that allows more options like:

- edit the `Custom User`
- Add models 
- Generate APIs
- Control the deployment 
  - Docker
  - CI/CD Scripts 

The `Django Cookie-Cutter` repo will be soon archived 

For support, please access: 
https://appseed.us/support/ 

Ty!
