### ISSUE TITLE
Data not displayed in Index.html

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-datta-able#32]
> Issue raised in support (Discord)

Changes are saved in `test1` branch 

A new model data [Site](https://github.com/app-generator/django-datta-able/blob/86b8bdf846e0ab5fb84d0c51072fff9ae7f516c9/home/models.py#L14) is displayed in index page. 

> Views.py

```py
  units = Site.objects.all().values()

  context = {
    'segment': 'index',
    'units'  : units    
  }
  return render(request, "pages/index.html", context)
```

> Template, `pages/index.html`

```html
    {% for unit in units %}
    >> {{ unit.site_id }}, {{ unit.site_name }}, {{ unit.sitecol }}, {{ unit.lat }}, {{ unit.long }}
    <br/>
    {% endfor %}
```

@mominur-helios please take a look

**Comment by mominur-helios** [comment]
Comment out the `views` from `admin_datta` and import `views` from `home`.


Just like this

![Screenshot from 2023-07-27 17-01-03](https://github.com/app-generator/django-datta-able/assets/101915710/fcaefb73-fd04-4211-896a-a5bf062a8007)

**Comment by jorgeassuncao** [comment]
I've made the above changes but the problem persists.

Do you need anything from me to help debig this? the complete `views.py`, `index.html`,...?

**Comment by app-generator** [comment]
Hello @jorgeassuncao 

The codebase will be updated soon. You've spotted a regression added by the latest commits.

Please wait.

**Comment by app-generator** [comment]
Fixed in version `v1.0.23`.

To test, please do the following & let us know the results.

- download the latest version
- create two Products using Django CLI or Admin Section
- Edit `home/views.py` to load `products` into the main template 

```py
def index(request):

  context = {
    'segment'  : 'index',
    'products' : Product.objects.all()  # <-- Uncomment this line
  }
  return render(request, "pages/index.html", context)
```

<br />

> The HOMEpage needs to be like this:
 
![image](https://github.com/app-generator/django-datta-able/assets/51070104/0df6637c-2909-445f-8088-c413c4fa89b9)

**Comment by jorgeassuncao** [comment]
Had this errors rinning `pip3 install -r requirements.txt`. Are they normal?

```Installing collected packages: django-admin-datta, tzdata, six, python-dotenv, pyparsing, pillow, packaging, numpy, kiwisolver, fonttools, cycler, python-dateutil, djangorestframework, contourpy, pandas, matplotlib, django-api-generator, django-dynamic-datatb
  DEPRECATION: django-admin-datta is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for django-admin-datta ... done
  DEPRECATION: django-api-generator is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for django-api-generator ... done
  DEPRECATION: django-dynamic-datatb is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by app-generator** [comment]
This is new. Let us investigate.

@mominur-helios please take a look at this warning.  

TY

**Comment by jorgeassuncao** [comment]
> This is new. Let us investigate.
> 
> @mominur-helios please take a look at this warning.
> 
> TY

![image](https://github.com/app-generator/django-datta-able/assets/7755388/91131c7b-b210-403f-85eb-25f7fc479621)

**Comment by app-generator** [comment]
Is the line UNcommented in the controller?

Products are not injected by default. 

```py
def index(request):

  context = {
    'segment'  : 'index',
    'products' : Product.objects.all()  # <-- Uncomment this line
  }
  return render(request, "pages/index.html", context)
```

**Comment by jorgeassuncao** [comment]
Yes it is.
![image](https://github.com/app-generator/django-datta-able/assets/7755388/e6dd4def-de36-47fc-b0b4-eee9a6510825)

**Comment by app-generator** [comment]
Can you share your repo with us? 

Just add `app-generator` as contributor.

**Comment by jorgeassuncao** [comment]
It's done.

https://github.com/jorgeassuncao/d23e8dd6-1347-499f-85bb-88bb4507108c

**Comment by app-generator** [comment]
The project is updated, please pull.

https://github.com/jorgeassuncao/d23e8dd6-1347-499f-85bb-88bb4507108c

You were still using the previous version. Now is updated to the latest release of Datta Able.

We recommend starting fresh with the latest version of Datta Able and adding your own code on top: 

![image](https://github.com/app-generator/django-datta-able/assets/51070104/5783f720-40f9-4a7c-afc4-cf26c6da619f)

**Comment by jorgeassuncao** [comment]
ahhhh... Perfect!
![image](https://github.com/app-generator/django-datta-able/assets/7755388/0464b5c1-7c87-4d50-92a4-7fbad380b062)

I'm still new to this all Django stuff, so maybe i've made a mistake along the way. Sorry for the trouble...

Just a quick question, if i use more than one "query" on a page (results from diferent tables) whats the corret way to do it? Just add them like these?

```python
def index(request):

  context = {
    'segment'  : 'index',
    'products' : Product.objects.all(),
    'services' : Service.objects.all()
  }
  return render(request, "pages/index.html", context)
```

And how to make a "query" available on all pages?

**Comment by app-generator** [comment]
@mominur-helios can you advice here?

**Comment by mominur-helios** [comment]
Hello @jorgeassuncao ,

if you use more than one "query" on a page then yes your approach is correct.

and if you want to make a "query" available on all pages then there is concept in django `templatetags`. You need to use `django custom templatetags` to achieve the expected behaviour.

**Comment by app-generator** [comment]
Patch validated. Closing.
@jorgeassuncao let us know anytime if you need further assistance.
