### ISSUE TITLE
this app is really good, I am new here, and I want to try to use docker to start this app 

### ISSUE THREAD

**Issue by snow-bean** [app-generator/django-datta-able#35]
nginx: [emerg] host not found in upstream "appseed_app:5005" in /etc/nginx/conf.d/appseed-app.conf:2

there is something wrong , what should I do, thanks ahead.

**Comment by app-generator** [comment]
Hello @snow-bean 

We'll get back after tests.

**Comment by app-generator** [comment]
Hello @snow-bean 

The App starts successfully on Windows/WSL and Ubuntu using:

```bash
$ chmod +x entrypoint.sh
$ docker-compose up --build 
```

In your case, seems the HOST is not resolved during Docker exec. Can you provide more input? 

- OS
- Docker version
- Docker-Compose version
- Full error log. 

TY!

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
