### ISSUE TITLE
admin_datta.forms could not be resolved

### ISSUE THREAD

**Issue by bahrom04** [app-generator/django-datta-able#38]
when i run `pip install -r requirements.txt` i got this:
Using legacy 'setup.py install' for django-admin-datta, since package 'wheel' is not installed.
Using legacy 'setup.py install' for django-dynamic-datatb, since package 'wheel' is not installed.
Using legacy 'setup.py install' for django-api-generator, since package 'wheel' is not installed.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
