### ISSUE TITLE
Logout not working in Django 5

### ISSUE THREAD

**Issue by koffisani** [app-generator/django-datta-able#39]
I just created a project with this template and Django 5 is return 405 erro code. Digging closer, I can see that GET method is not allowed for logging out a user.

Anyone with this issue ? How did you fix it ?

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
