### ISSUE TITLE
Having trouble getting datatables to work

### ISSUE THREAD

**Issue by jswift24** [app-generator/django-datta-able#45]
I'm trying to get datatable functionality, using [zero configuration, like in this doc](https://django-datta-able-enh.appseed-srv1.com/table-dt_basic.html).

I'm using the following code:
```
<link rel="stylesheet" href="https://appsrv1-147a1.kxcdn.com/django-datta-able-enh/css/plugins/dataTables.bootstrap5.min.css">
...
            <table id="criteria-table" class="table table-hover dataTables_wrapper dt-bootstrap5">
              <thead>
                <tr class="bg-c-gray-900">
                  <th class="strong text-c-black col-2">Name</th>
                  <th class="strong text-c-black col-1">Type</th>                  
                  <th class="strong text-c-black">Description</th>                  
                </tr>
              </thead>
              <tbody>
...
<script>
  $('#criteria-table').DataTable();
  console.log(table);
</script>
```

However, my console says
`TypeError: $(...).DataTable is not a function`
...and none of the datatable features are working.

What am I missing? Please help.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
