### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by jisoooh0202** [app-generator/django-datta-able#46]
Hello, contributors.
Thanks for your work.
Just want to mention the python version needs to be updated.
As you can see in the screenshot below, I get error when I run it in docker.
If I change the python version in dockerfile, it works.

![image](https://github.com/user-attachments/assets/d1f9ace2-bf67-4c25-98a3-a0078a74520e)

**Comment by app-generator** [comment]
Noted the above @jisoooh0202. Ty for the fix proposal.

The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
